config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "pages#home"

  resources :leads, only: [:index, :show, :edit, :update] do
    resources :orders, only: [:new, :create]
    resources :lnotes, only: [:new, :create]
  end
  # resources :lnotes, only: [:new, :create]
  resources :customers, only: [:index, :new, :create, :edit, :update] do
    resources :leads, only: [:new, :create]
  end
  resources :customers, only: [:edit, :update]

  resources :orders, only: [:show, :edit, :update] do
    resources :items, only: [:new, :create]
    resources :onotes, only: [:new, :create]
  end

  resources :items, only: [:edit, :update, :destroy]
  resources :products, only: [:index, :new, :create]

  get 'dashboard', to: 'pages#dashboard'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" id="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_leadstatus.html.erb
<% if @lead.status === "New" %>
      <p>Status: <span class= "status-tag new-tag"><%= @lead.status %></span></p>
    <% elsif @lead.status === "Going"%>
      <p>Status: <span class= "status-tag going-tag"><%= @lead.status %></span></p>
    <% elsif @lead.status === "Lost"%>
      <p>Status: <span class= "status-tag lost-tag"><%= @lead.status %></span></p>
    <% elsif @lead.status === "Won" || @lead.status === "Completed" %>
      <p>Status: <span class= "status-tag won-tag"><%= @lead.status %></span></p>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to dashboard_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-gauge-high" style="color:white"></i>
      <% if user_signed_in? %>
        <span style="color:white" >Dashboard</span>
      <% end %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= link_to "Home", root_path, class: "nav-link mx-2" %>
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "sacalpel.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Customers", customers_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_orderstatus.html.erb
<% if @order.status === "New" %>
            <p>Status: <span class= "status-tag new-tag"><%= @order.status %></span></p>
          <% elsif @order.status === "Going"%>
            <p>Status: <span class= "status-tag going-tag"><%= @order.status %></span></p>
          <% elsif @order.status === "Canceled"%>order
            <p>Status: <span class= "status-tag lost-tag"><%= @order.status %></span></p>
          <% elsif @order.status === "Completed"%>
            <p>Status: <span class= "status-tag won-tag"><%= @order.status %></span></p>
<% end %>