config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "pages#home"

  resources :leads, only: [:index, :show, :edit, :update] do
    resources :orders, only: [:new, :create]
    resources :lnotes, only: [:new, :create]
  end
  # resources :lnotes, only: [:new, :create]
  resources :customers, only: [:index, :new, :create, :edit, :update] do
    resources :leads, only: [:new, :create]
  end
  resources :customers, only: [:edit, :update]

  resources :orders, only: [:show, :edit, :update] do
    resources :items, only: [:new, :create]
    resources :onotes, only: [:new, :create]
  end

  resources :items, only: [:edit, :update, :destroy]
  resources :products, only: [:index, :new, :create]

  get 'dashboard', to: 'pages#dashboard'
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :user
  belongs_to :customer
  has_many :orders
  has_many :complaints
  has_many :lnotes
  validates :status, presence: true
  validates :status, inclusion:
  { in: ["New", "Going", "Won", "Lost", "Completed"],
    message: "Invalid" }

  include PgSearch::Model

  pg_search_scope :global_search,
    associated_against:
    { customer: [ :name, :phone_number, :email, :address ],
      user: :name
    },
      using:
    {
        tsearch: { prefix: true }
    }
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_customer, only: [:new, :create]

  def index
    if params[:query].present?
      @leads = Lead.global_search(params[:query])
    else
      @leads = Lead.all
    end
  end

  def show
    @lead = Lead.find(params[:id])
    @lnotes = @lead.lnotes
    @lead_orders = @lead.orders
    @lnote = Lnote.new
    @order = Order.new
  end

  def new
    @lead = Lead.new
  end

  def create
    @lead = Lead.new(lead_params)
    @lead.user = current_user
    @lead.customer = @customer
    @lead.status = "New"
    if @lead.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @lead = Lead.find(params[:id])
  end

  def update
    @lead = Lead.find(params[:id])
    if @lead.update(lead_params)
      redirect_to lead_path(@lead)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_customer
    @customer = Customer.find(params[:customer_id])
  end

  def lead_params
    params.require(:lead).permit(:status, :comments, :follow_up_date, :follow_up_time)
  end
end

app/views/leads/dashboard.erb
<div class="container mb-3  ">
  <div class="main-container">
    <div class="my-3">
      <%= link_to customers_path, class:"btn btn-flat-small" do %>
        <i class="fa-solid fa-users"></i> Customers
      <% end %>
      <%= link_to customers_path, class:"btn btn-flat-small" do %>
        <i class="fa-sharp fa-solid fa-file-invoice"></i> Orders
      <% end %>
      <%= link_to customers_path, class:"btn btn-flat-small" do %>
        <i class="fa-solid fa-tag"></i> Producst
      <% end %>
    </div>
    <div class="row">
      <div class="col-6">
        <ul class="list-group">
          <% @newleads.each do |lead| %>
            <li class="list-group-item">
                <p><%= lead.customer.name%>
                  <% if lead.status ==="New" %>
                      <span class= "status-tag new-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Going"%>
                      <span class= "status-tag going-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Lost"%>
                      <span class= "status-tag lost-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Won"%>
                      <span class= "status-tag won-tag"><%= lead.status %></span>
                  <% end %>
                </p>
                <p><%= lead.customer.phone_number%> | <%= lead.customer.email %></p>
                <p>Orders: <%= lead.orders.count %></p>
                <%= link_to "Go", lead_path(lead), class: "btn btn-flat"%>
            </li>
          <% end %>
        </ul>
      </div>
    <div class="col-6">
        <ul class="list-group">
          <% @goingleads.each do |lead| %>
            <li class="list-group-item">
                <p><%= lead.customer.name%>
                  <% if lead.status ==="New" %>
                      <span class= "status-tag new-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Going"%>
                      <span class= "status-tag going-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Lost"%>
                      <span class= "status-tag lost-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Won"%>
                      <span class= "status-tag won-tag"><%= lead.status %></span>
                  <% end %>
                </p>
                <p><%= lead.customer.phone_number%> | <%= lead.customer.email %></p>
                <p>Orders: <%= lead.orders.count %></p>
                <%= link_to "Go", lead_path(lead), class: "btn btn-flat"%>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/leads/edit.html.erb
<div class="container main-container my-5">
  <h1><%= @lead.customer.name %></h1>
  <h4><%= @lead.customer.phone_number %> | <%= @lead.customer.email %></h4>
  <p><%= @lead.customer.address %></p>
  <div class="col-6">
    <%= simple_form_for @lead do |f| %>
    <%= f.input :status, collection: [ "New", "Going", "Won", "Lost", "Completed" ] %>
    <%= f.association :user, collection: User.order(:name) %>
    <%= f.input :follow_up_date, html5: true%>
    <%= f.input :follow_up_time, html5: true %>
    <%= f.input :comments %>
    <%= f.button :submit, class: "btn btn-flat"  %>
    <%= link_to "Cancel", lead_path(@lead), class: "btn btn-flat" %>
    <% end %>
  </div>
</div>

app/views/leads/index.html.erb
<div class="main-container my-3">
  <div class="container">
    <h1>Leads</h1>
    <%= form_with url: "#", method: :get, class: "d-flex col-6  mb-2" do %>
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a lead" %>
      <%= submit_tag "Search", class: "btn btn-flat-small" %>
    <% end %>
    <ul class="list-group">
      <% @leads.each do |lead| %>
        <li class="list-group-item">
            <p><%= lead.customer.name%>
              <% if lead.status ==="New" %>
                  <span class= "status-tag new-tag"><%= lead.status %></span>
                <% elsif lead.status ==="Going"%>
                  <span class= "status-tag going-tag"><%= lead.status %></span>
                <% elsif lead.status ==="Lost"%>
                  <span class= "status-tag lost-tag"><%= lead.status %></span>
                <% elsif lead.status ==="Won"%>
                  <span class= "status-tag won-tag"><%= lead.status %></span>
              <% end %>
            </p>
            <p><%= lead.customer.phone_number%> | <%= lead.customer.email %></p>
            <p>Orders: <%= lead.orders.count %></p>
            <%= link_to "Go", lead_path(lead), class: "btn btn-flat"%>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/leads/new.html.erb
<div class="container main-container mt-5">
  <h1><%= @customer.name %></h1>
  <h4><%= @customer.phone_number %> | <%= @customer.email %></h4>
  <p><%= @customer.address %></p>
  <div class="col-6">
    <%= simple_form_for [@customer, @lead] do |f| %>
    <%= f.input :follow_up_date, html5: true %>
    <%= f.input :follow_up_time, html5: true %>
    <%= f.input :comments %>
    <%= f.button :submit, class: "btn btn-flat" %>
    <%= link_to "Cancel", customers_path, class: "btn btn-flat"%>
    <% end %>
  </div>
</div>

app/views/leads/show.html.erb
<div class="container main-container my-4">
  <%=link_to dashboard_path do%>
  <i class="fa-sharp fa-solid fa-arrow-left me-3"></i>Back
  <% end %>
  <div class="row">
    <div class="col-6">
      <h1><%= @lead.customer.name %></h1>
          <%= render "shared/leadstatus" %>
      <p><%= @lead.customer.phone_number %></p>
      <p><%= @lead.customer.email %></p>
      <p><%= @lead.customer.address %></p>
      <p class="time-stamp">created-<%= @lead.created_at.localtime.strftime('%b %d %Y %H:%M') %></p>
      <%= link_to "Edit", edit_lead_path(@lead) , class: "btn btn-flat" %>
      <% if @lead_orders.empty? %>
          <p class= "my-3">No orders created</p>
      <% else %>
        <p class= "my-3">
          <% @lead_orders.each do |order| %>
              <%= link_to "Order_ID#{order.id}_#{order.status} |", order_path(order) %>
          <% end %>
        </p>
      <% end %>
      <div class= "my-3">
        <%= simple_form_for [@lead, @order] do |f| %>
          <%= f.button :submit, class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
    <div class="col-6">
      <div class="scroll-card-comments">
        <p><%= @lead.comments %></p>
      </div>
    </div>
  </div>
  <div class="my-4">
    <%= simple_form_for [@lead, @lnote] do |f|  %>
      <%= f.input :note  %>
      <%= f.button :submit, value: "Add Note", class: "btn btn-flat" %>
    <% end %>
    <ul class="list-group mt-4" data-controller="lnotes">
      <% @lnotes.order(created_at: :desc).each do |lnote| %>
        <li class="list-group-item">
        <h5 class="time-stamp">
        <%= lnote.created_at.localtime.strftime('%b %d %Y %H:%M') %>
        <%= lnote.user.name %>
        </h5>
        <p><%= lnote.note %></p>
        </li>
      <% end %>
    </ul>
  </div>
</div>