config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "pages#home"

  resources :leads, only: [:index, :show, :edit, :update] do
    resources :orders, only: [:new, :create]
    resources :lnotes, only: [:new, :create]
  end
  # resources :lnotes, only: [:new, :create]
  resources :customers, only: [:index, :new, :create, :edit, :update] do
    resources :leads, only: [:new, :create]
  end
  resources :customers, only: [:edit, :update]

  resources :orders, only: [:show, :edit, :update] do
    resources :items, only: [:new, :create]
    resources :onotes, only: [:new, :create]
  end

  resources :items, only: [:edit, :update, :destroy]
  resources :products, only: [:index, :new, :create]

  get 'dashboard', to: 'pages#dashboard'
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :leads
  has_many :orders, through: :leads
  has_many :complaints, through: :leads
  validates :name, :phone_number, :email, :address, presence: true
  validates :email, :phone_number, :address, uniqueness: true
  validates :email, format: { with: /\A\S+@\S+\z/, message: "-Please eneter a valid email" }
  validates :phone_number, format: { with: /\A\d{10}\z/, message: "-Please enter a valid 10 digits number" }
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customers_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customers_path
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :phone_number, :email, :address)
  end
end

app/views/customers/edit.html.erb
<div class="container main-container">
  <div class="d-flex justify-content-center">
    <h1 class= "my-3">Edit Customer</h1>
  </div>
    <div class="d-flex justify-content-center">
      <div class="col-6">
        <%= simple_form_for @customer do |f| %>
          <%= f.input :name, required: true %>
          <%= f.input :phone_number, hint: '10 digits phone number, no especial characters', required: true %>
          <%= f.input :email, required: true %>
          <%= f.input :address, required: true %>
          <%= f.button :submit, class: "btn btn-flat" %>
          <%= link_to "Cancel", customers_path, class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
</div>

app/views/customers/index.html.erb
  <div class="container col-8 main-container my-3">
    <h1 class="my-2">Customers List</h1> <%= link_to "New Customer", new_customer_path(@customer), class: "btn btn-flat-small mb-2" %>
      <ul class="list-group">
        <% @customers.each do |customer| %>
          <li class="list-group-item d-flex justify-content-between">
            <div>
              <p><%= customer.name %> | <%= customer.phone_number %></p>
              <p><%= customer.email %> | <%= customer.address %></p>
              <p>
                <%= link_to "New Lead", new_customer_lead_path(customer), class: "btn btn-flat-small" %>
                <%= link_to "Edit Customer", edit_customer_path(customer), class: "btn btn-flat-small" %>
              </p>
            </div>
          </li>
        <% end %>
      </ul>
  </div>

app/views/customers/new.html.erb
<div class="container main-container">
  <div class="d-flex justify-content-center">
    <h1 class= "my-3">New Customer</h1>
  </div>
    <div class="d-flex justify-content-center">
      <div class="col-6">
        <%= simple_form_for @customer do |f| %>
          <%= f.input :name, required: true %>
          <%= f.input :phone_number, hint: '10 digits phone number, no especial characters', required: true %>
          <%= f.input :email, required: true %>
          <%= f.input :address, required: true %>
          <%= f.button :submit, class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
</div>