config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "pages#home"

  resources :leads, only: [:index, :show, :edit, :update] do
    resources :orders, only: [:new, :create]
    resources :lnotes, only: [:new, :create]
  end
  # resources :lnotes, only: [:new, :create]
  resources :customers, only: [:index, :new, :create, :edit, :update] do
    resources :leads, only: [:new, :create]
  end
  resources :customers, only: [:edit, :update]

  resources :orders, only: [:show, :edit, :update] do
    resources :items, only: [:new, :create]
    resources :onotes, only: [:new, :create]
  end

  resources :items, only: [:edit, :update, :destroy]
  resources :products, only: [:index, :new, :create]

  get 'dashboard', to: 'pages#dashboard'
end

app/views/pages/dashboard.html.erb
<div class="container mb-3  ">
  <div class="main-container">
    <div class="my-3">
      <%= link_to customers_path, class:"btn btn-flat-small" do %>
        <i class="fa-solid fa-users"></i> Customers
      <% end %>
      <%= link_to customers_path, class:"btn btn-flat-small" do %>
        <i class="fa-sharp fa-solid fa-file-invoice"></i> Orders
      <% end %>
      <%= link_to products_path, class:"btn btn-flat-small" do %>
        <i class="fa-solid fa-tag"></i> Products
      <% end %>
    </div>
    <div class="row">
      <div class="col-4">
        <ul class="list-group">
          <% @newleads.each do |lead| %>
            <li class="list-group-item">
                <p><%= lead.customer.name%>
                  <% if lead.status ==="New" %>
                      <span class= "status-tag new-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Going"%>
                      <span class= "status-tag going-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Lost"%>
                      <span class= "status-tag lost-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Won"%>
                      <span class= "status-tag won-tag"><%= lead.status %></span>
                  <% end %>
                </p>
                <p><%= lead.customer.phone_number%> | <%= lead.customer.email %></p>
                <p>Orders: <%= lead.orders.count %></p>
                <%= link_to "Go", lead_path(lead), class: "btn btn-flat"%>
            </li>
          <% end %>
        </ul>
      </div>
    <div class="col-4">
        <ul class="list-group">
          <% @goingleads.each do |lead| %>
            <li class="list-group-item">
                <p><%= lead.customer.name%>
                  <% if lead.status ==="New" %>
                      <span class= "status-tag new-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Going"%>
                      <span class= "status-tag going-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Lost"%>
                      <span class= "status-tag lost-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Won"%>
                      <span class= "status-tag won-tag"><%= lead.status %></span>
                  <% end %>
                </p>
                <p><%= lead.customer.phone_number%> | <%= lead.customer.email %></p>
                <p>Orders: <%= lead.orders.count %></p>
                <%= link_to "Go", lead_path(lead), class: "btn btn-flat"%>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="col-4">
        <ul class="list-group">
          <% @wonleads.each do |lead| %>
            <li class="list-group-item">
                <p><%= lead.customer.name%>
                  <% if lead.status ==="New" %>
                      <span class= "status-tag new-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Going"%>
                      <span class= "status-tag going-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Lost"%>
                      <span class= "status-tag lost-tag"><%= lead.status %></span>
                    <% elsif lead.status ==="Won"%>
                      <span class= "status-tag won-tag"><%= lead.status %></span>
                  <% end %>
                </p>
                <p><%= lead.customer.phone_number%> | <%= lead.customer.email %></p>
                <p>Orders: <%= lead.orders.count %></p>
                <%= link_to "Go", lead_path(lead), class: "btn btn-flat"%>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="main-container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80);">
    <div class="container">
      <h1><strong>Scalpel_CRM</strong> Business intelligence</h1>
      <p>Customer relationship management application for entrepreneurs</p>
      <% unless user_signed_in?%>
        <%= link_to "Sign Up", new_user_registration_path ,class: "btn btn-flat"  %>
      <% end %>
    </div>
  </div>
</div>